### PR TITLE
Django 1.8

### PR DESCRIPTION
**Pull request by diefenbach**
See also https://github.com/diefenbach/lfs-buildout-development/tree/django-1.8

### CODE REVIEW

**Comment by pigletto** [comment]
Regarding migration of South migrations to Django ones we should also create initial migrations as described here: https://docs.djangoproject.com/en/dev/topics/migrations/#upgrading-from-south

**Comment by diefenbach** [comment]
Yeah, I've read that too. We can do that, but I can't see any advantage or reason. Do you know why?

**Comment by pigletto** [comment]
If we don't have initial migrations then any further change in models will require creation of them anyway (prior to the real migration). 
It seems better to me to have clean baseline with all these migrations from the beginning. This way --fake will have to be done once during switch to new LFS release (eg. in lfs_migrate script).

**Comment by diefenbach** [comment]
Got it. I'll add them. Thx so far.

**Pull request merged**
