### PR TITLE
Feature/django 1.10

### PR DESCRIPTION
**Pull request by diefenbach**

### CODE REVIEW

**Comment by pigletto** [comment]
1. Pagination for Search page should be reimplemented with django's builtin pagination modules

1. Possibly `"STATIC_URL": context.get("STATIC_URL")` lines should be removed from lfs_tags as it doesn't seem to be used and it relies on **django.template.context_processors.static** context processor that is not included in default settings from installation docs

1. All occurences of {{ STATIC_URL }} in documentation should be replaced with {% static '...' %} for consistency with lfs-theme and because of lack of **django.template.context_processors.static** context processor within default settings from installation instructions

**Comment by diefenbach** [comment]
Good points. Will take care of them.

**Comment by diefenbach** [comment]
1. Fixed.

**Comment by diefenbach** [comment]
2 + 3. Fixed

**Comment by diefenbach** [comment]
Please be aware that I resolved conflicts and forced pushed this branch.

**Comment by pigletto** [comment]
setup.py does not define specific version of Django as a requirement. Because of that Django 1.10 is installed as a dependency of django-localflavour which might cause issues as soon as next Django release appears

**Comment by diefenbach** [comment]
Fixed

**Comment by pigletto** [comment]
Using $.growl doesn't seem to work:

https://github.com/diefenbach/django-lfs/commit/931eaedaf57d2a822a14c2cfc2cd36947523de2d

**Comment by pigletto** [comment]
LGTM :)

**Pull request merged**
